import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Header/Navbar';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className='max-w-6xl mx-auto'>{children}</main>
      </body>
    </html>
  );
}
